name: Build on New Nextcloud Image with SMB client and cron

on:
  schedule:
    - cron: '0 13,23 * * *'
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  actions: read

env:
  BUILDKIT_PROGRESS: plain
  NC_VERSION: .github/.state/.last_release_nc

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      build_needed: ${{ steps.check.outputs.build_needed }}
      current_timestamp: ${{ steps.check.outputs.current_timestamp }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch latest image timestamp
        id: check
        run: |
          API_URL="https://hub.docker.com/v2/repositories/library/nextcloud/tags/apache/"
          response=$(curl -s "$API_URL")
          current_timestamp=$(echo "$response" | jq -r '.last_updated')
          echo "Current timestamp: $current_timestamp"

          mkdir -p "$(dirname "$NC_VERSION")"

          if [ -f "$NC_VERSION" ]; then
            previous_timestamp=$(cat "$NC_VERSION")
            echo "Previous timestamp: $previous_timestamp"

            if [ "$current_timestamp" != "$previous_timestamp" ]; then
              echo "build_needed=true" >> "$GITHUB_OUTPUT"
            else
              echo "build_needed=false" >> "$GITHUB_OUTPUT"
            fi
          else
            echo "First run - build needed"
            echo "build_needed=true" >> "$GITHUB_OUTPUT"
          fi

          echo "current_timestamp=$current_timestamp" >> "$GITHUB_OUTPUT"

  build:
    needs: check-version
    if: needs.check-version.outputs.build_needed == 'true'
    runs-on: ubuntu-latest
    env:
      CURRENT_TIMESTAMP: ${{ needs.check-version.outputs.current_timestamp }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      - name: Build and push image
        run: |
          if [ -z "$CURRENT_TIMESTAMP" ]; then
            echo "Missing CURRENT_TIMESTAMP, aborting."
            exit 1
          fi

          SAFE_TAG=$(date -u -d "$CURRENT_TIMESTAMP" +%Y%m%d)
          echo "Building with tags: apache and $SAFE_TAG"

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --provenance=false \
            --sbom=false \
            --tag ghcr.io/${{ github.repository_owner }}/nextcloud-full:apache \
            --tag ghcr.io/${{ github.repository_owner }}/nextcloud-full:$SAFE_TAG \
            --push \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            --file ./NextCloud.Dockerfile

  update-checkpoint:
    needs: [check-version, build]
    if: needs.check-version.outputs.build_needed == 'true'
    runs-on: ubuntu-latest
    env:
      CURRENT_TIMESTAMP: ${{ needs.check-version.outputs.current_timestamp }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update last_checked file
        run: |
          mkdir -p "$(dirname "$NC_VERSION")"
          echo "$CURRENT_TIMESTAMP" > "$NC_VERSION"

          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git pull --quiet
          git add -f "$NC_VERSION"
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Update .last_release to $CURRENT_TIMESTAMP"
          git push origin HEAD:${GITHUB_REF} --no-verify
